version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: revest
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
